; ==========================================
; Generated by LycoScript Enterprise Compiler
; Target: Lyco-8 Fantasy Console
; ==========================================

; --- Kernel ROM Routines (Standard Library) ---
print = $FFD2    ; Standard character output routine
delay = $FF00    ; System delay/vsync routine

* = $8000

    JMP main

    LDA #$04
    LDA #$05
    LDA #$06
; --- Function: main ---
main:
    JSR print
    LDA #$00
WHILE_START_0:
    LDA #$01
    CMP #$00
    BEQ WHILE_END_1
    LDA #$00
    STA $01    ; Store in pixelIndex
WHILE_START_2:
    LDA #$FF
    CMP #$00
    BEQ WHILE_END_3
    ; Simplified Absolute Store
    STA $2000
    LDA #$01
    STA $01    ; Store in pixelIndex
    JMP WHILE_START_2
WHILE_END_3:
    ; Simplified Absolute Store
    STA $2000
    STA $00    ; Store in currentColor
    STA $00    ; Store in currentColor
    STA $00    ; Store in currentColor
    JSR delay
    JMP WHILE_START_0
WHILE_END_1:
    RTS

