package it.lycoris.lycoscript.compiler.semantic;

import it.lycoris.lycoscript.compiler.parser.LycoScriptBaseVisitor;
import it.lycoris.lycoscript.compiler.parser.LycoScriptParser;

/**
 * Traverses the Abstract Syntax Tree (AST) to generate 6502 Assembly code.
 * Implements strict memory mapping for intrinsic system functions (Kernel ROM).
 */
public class CodeGenerator extends LycoScriptBaseVisitor<Void> {
    private final StringBuilder assemblyOutput;
    private final SymbolTable symbolTable;
    private int labelCounter;

    /**
     * Initializes the Code Generator.
     *
     * @param symbolTable The symbol table containing resolved variables and constants.
     */
    public CodeGenerator(SymbolTable symbolTable) {
        this.symbolTable = symbolTable;
        this.assemblyOutput = new StringBuilder();
        this.labelCounter = 0;

        this.writeHeader();
    }

    /**
     * Retrieves the final generated Assembly source code.
     *
     * @return A string containing the formatted 6502 Assembly code.
     */
    public String getGeneratedCode() {
        return this.assemblyOutput.toString();
    }

    /**
     * Writes the initial boot sequence, kernel mappings, and program origin.
     */
    private void writeHeader() {
        this.assemblyOutput.append("; ==========================================\n");
        this.assemblyOutput.append("; Generated by LycoScript Enterprise Compiler\n");
        this.assemblyOutput.append("; Target: Lyco-8 Fantasy Console\n");
        this.assemblyOutput.append("; ==========================================\n\n");

        // --- KERNEL ABI (Application Binary Interface) MAPPINGS ---
        this.assemblyOutput.append("; --- Kernel ROM Routines (Standard Library) ---\n");
        // Using upper-case for constants is standard 6502 convention and
        // prevents the Assembler from throwing 'Symbol not resolved'
        this.assemblyOutput.append("print = $FFD2    ; Standard character output routine\n");
        this.assemblyOutput.append("delay = $FF00    ; System delay/vsync routine\n\n");

        // --- PROGRAM ORIGIN ---
        this.assemblyOutput.append("* = $8000\n\n");

        // Jump to the main function to bypass any subroutine definitions
        this.assemblyOutput.append("    JMP main\n\n");
    }

    /**
     * Generates a unique label name for branching instructions.
     *
     * @param prefix The descriptive prefix for the label.
     * @return A unique label string.
     */
    private String generateUniqueLabel(String prefix) {
        int currentCount = this.labelCounter;
        this.labelCounter++;
        return prefix + "_" + currentCount;
    }

    @Override
    public Void visitFunctionDecl(LycoScriptParser.FunctionDeclContext ctx) {
        String functionName = ctx.IDENTIFIER().getText();

        this.assemblyOutput.append("; --- Function: ").append(functionName).append(" ---\n");
        this.assemblyOutput.append(functionName).append(":\n");

        this.visit(ctx.block());

        this.assemblyOutput.append("    RTS\n\n");

        return null;
    }

    @Override
    public Void visitAssignmentStatement(LycoScriptParser.AssignmentStatementContext ctx) {
        String variableName = ctx.IDENTIFIER().getText();
        Symbol symbol = this.symbolTable.resolve(variableName);

        this.visit(ctx.expression(ctx.expression().size() - 1));

        if (symbol instanceof VariableSymbol variableSymbol) {
            int address = variableSymbol.memoryAddress();
            this.assemblyOutput.append("    STA $")
                    .append(String.format("%02X", address))
                    .append("    ; Store in ").append(variableName).append("\n");
        } else if (symbol instanceof ConstantSymbol constantSymbol) {
            // Simplified Absolute, Y-Indexed for array access is required for production
            int baseAddress = constantSymbol.value();
            this.assemblyOutput.append("    ; Simplified Absolute Store\n");
            this.assemblyOutput.append("    STA $")
                    .append(String.format("%04X", baseAddress))
                    .append("\n");
        }

        return null;
    }

    @Override
    public Void visitNumberExpr(LycoScriptParser.NumberExprContext ctx) {
        int value = Integer.parseInt(ctx.getText());
        this.assemblyOutput.append("    LDA #$")
                .append(String.format("%02X", value))
                .append("\n");
        return null;
    }

    @Override
    public Void visitHexExpr(LycoScriptParser.HexExprContext ctx) {
        String hexString = ctx.getText().replace("$", "");
        int value = Integer.parseInt(hexString, 16);
        this.assemblyOutput.append("    LDA #$")
                .append(String.format("%02X", value))
                .append("\n");
        return null;
    }

    @Override
    public Void visitFunctionCallStatement(LycoScriptParser.FunctionCallStatementContext ctx) {
        String functionName = ctx.functionCall().IDENTIFIER().getText();

        // The JSR will now successfully resolve to the memory mapped constants
        this.assemblyOutput.append("    JSR ").append(functionName).append("\n");

        return null;
    }

    @Override
    public Void visitWhileStatement(LycoScriptParser.WhileStatementContext ctx) {
        String loopStartLabel = this.generateUniqueLabel("WHILE_START");
        String loopEndLabel = this.generateUniqueLabel("WHILE_END");

        this.assemblyOutput.append(loopStartLabel).append(":\n");

        this.visit(ctx.expression());

        this.assemblyOutput.append("    CMP #$00\n");
        this.assemblyOutput.append("    BEQ ").append(loopEndLabel).append("\n");

        this.visit(ctx.block());

        this.assemblyOutput.append("    JMP ").append(loopStartLabel).append("\n");
        this.assemblyOutput.append(loopEndLabel).append(":\n");

        return null;
    }
}