package it.lycoris.lycoscript.compiler.semantic;

import it.lycoris.lycoscript.compiler.parser.LycoScriptBaseVisitor;
import it.lycoris.lycoscript.compiler.parser.LycoScriptParser;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Traverses the Abstract Syntax Tree (AST) generated by ANTLR4 to perform semantic analysis.
 * Validates types, enforces scoping rules, and populates the Symbol Table.
 */
public class SemanticAnalyzer extends LycoScriptBaseVisitor<Void> {
    private static final Logger LOG = LoggerFactory.getLogger(SemanticAnalyzer.class);
    private final SymbolTable symbolTable;
    // Simplistic memory allocator for Zero Page variables (starts at $00)
    private int currentZeroPageAddress = 0x00;

    public SemanticAnalyzer(SymbolTable symbolTable) {
        this.symbolTable = symbolTable;
    }

    @Override
    public Void visitConstantDecl(LycoScriptParser.ConstantDeclContext ctx) {
        String name = ctx.IDENTIFIER().getText();
        DataType type = this.parseType(ctx.type());

        // Extract the raw string, remove the '$' prefix, and parse as Hex
        String hexValueStr = ctx.expression().getText().replace("$", "");
        int value = Integer.parseInt(hexValueStr, 16);

        ConstantSymbol constant = new ConstantSymbol(name, type, value);
        this.symbolTable.define(constant);

        return super.visitConstantDecl(ctx);
    }

    @Override
    public Void visitVariableDecl(LycoScriptParser.VariableDeclContext ctx) {
        String name = ctx.IDENTIFIER().getText();
        DataType type = this.parseType(ctx.type());

        // Allocate memory dynamically in the Zero Page
        int memoryAddress = this.currentZeroPageAddress;

        // A byte takes 1 address space, a pointer takes 2
        this.currentZeroPageAddress += (type == DataType.POINTER) ? 2 : 1;

        if (this.currentZeroPageAddress > 0xFF) {
            throw new IllegalStateException("Compilation Error: Zero Page memory exhausted.");
        }

        VariableSymbol variable = new VariableSymbol(name, type, memoryAddress);
        this.symbolTable.define(variable);

        return super.visitVariableDecl(ctx);
    }

    @Override
    public Void visitFunctionDecl(LycoScriptParser.FunctionDeclContext ctx) {
        String name = ctx.IDENTIFIER().getText();
        DataType returnType = this.parseType(ctx.type());

        FunctionSymbol function = new FunctionSymbol(name, returnType);
        this.symbolTable.define(function);

        return super.visitFunctionDecl(ctx);
    }

    @Override
    public Void visitIdExpr(LycoScriptParser.IdExprContext ctx) {
        // Semantic Check: Validate that variables used in expressions actually exist
        String name = ctx.IDENTIFIER().getText();
        this.symbolTable.resolve(name); // Will throw an exception if undefined

        return super.visitIdExpr(ctx);
    }

    /**
     * Utility method to map AST type context to internal DataType enum.
     *
     * @param ctx The parsed type context.
     * @return The corresponding DataType.
     */
    private DataType parseType(LycoScriptParser.TypeContext ctx) {
        String typeString = ctx.getText();
        return switch (typeString) {
            case "byte" -> DataType.BYTE;
            case "pointer" -> DataType.POINTER;
            case "void" -> DataType.VOID;
            default -> throw new IllegalArgumentException("Unknown data type: " + typeString);
        };
    }
}